name: Lockfile sync

on:
  push:
    branches: [master]
    paths:
      - '.github/workflows/lockfile-sync.yml'

concurrency:
  group: lockfile-sync
  cancel-in-progress: true

jobs:
  release-runner:
    runs-on: [self-hosted, macOS, ARM64, bouncampus]
    steps:
      - run: echo "lockfile sync complete"
